app = "kaustuva"
kill_signal = "SIGINT"
kill_timeout = "5s"
primary_region = "syd"

[build]
image = "kausmoss/kaustuva:latest"

[env]
PORT = "8080"
IP = "0.0.0.0"
PRIMARY_REGION = "syd"

[[services]]
internal_port = 8_080
processes = [ "app" ]
protocol = "tcp"

  [services.concurrency]
  hard_limit = 25
  soft_limit = 20
  type = "connections"

  [[services.ports]]
  force_https = true
  handlers = [ "http" ]
  port = 80

  [[services.ports]]
  handlers = [ "tls", "http" ]
  port = 443